clean:
	rm -rf *.class
	rm -rf ./utils/*.class
	rm -rf ./operations/*.class
	rm -rf ./gui/*.class
	rm -rf ./exit_thread/*.class
	rm -rf ./entities/*.class
linecount:
	wc -l ./*.java
	wc -l ./utils/*.java
	wc -l ./operations/*.java
	wc -l ./gui/*.java
	wc -l ./exit_thread/*.java
	wc -l ./entities/*.java
